### PR TITLE
Make swagger-codegen version configurable

### PR DESCRIPTION
**Pull request by davschm**
Thanks for your consideration :smile:

### CODE REVIEW

**Comment by softprops** [comment]
Cool. Thanks for the patch are there any notable breaking changes between the version we we're using and the version you are defaulting to here I might need to communicate?

**Comment by davschm** [comment]
Hi Doug,
There were a bunch of breaking changes as per version 2.3.0:
[https://github.com/swagger-api/swagger-codegen/releases/tag/v2.3.0](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.3.0)
If that's a problem, how about making the version configurable, but defaulting to 2.2.2?
David

**Comment by softprops** [comment]
That sounds good

**Comment by softprops** [comment]
@davschm excellent!

**Pull request merged**
