### PR TITLE
support both openapi and swaager

### PR DESCRIPTION
**Pull request by yishanhe**
- support two providers by asking user to provide a
   provider[swagger, openapi] during the init the repository

### CODE REVIEW

**Comment by yishanhe** [comment]
This is related to addressing issue #27 , instead of deprecating, 
as swagger codegen is alive as well. might just support both.

**Comment by softprops** [comment]
@yishanhe thanks for pull. 

Would you be able to add a test case covering your changes to make sure these changes have the impact you're looking for and not regress the current rules? 

You can find the current test runner [here](https://github.com/meetup/rules_openapi/blob/master/test.sh)

**Comment by yishanhe** [comment]
@softprops agree with the test coverage requirements. when I looked at the existing tests, it is really trivial, current test is more like testing reproducibility (not functional correctness). any suggestion on tests that I can add? Thanks.

**Comment by softprops** [comment]
It may make sense to create a variation that test that uses the `openapi` provider

**Comment by softprops** [comment]
Thanks @yishanhe!

**Pull request merged**
